//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_Product
    {
        public int idComment { get; set; }
        public string contentCmt { get; set; }
        public int idAccount { get; set; }
        public int idProduct { get; set; }
        public bool hideCmt { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Product Product { get; set; }
    }
}
