//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoAccount
    {
        public int idSql { get; set; }
        public string PhoneNumber { get; set; }
        public string Fullname { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Address { get; set; }
        public int idRole { get; set; }
        public int idAccount { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Role Role { get; set; }
    }
}
