//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class listShip
    {
        public int idShip { get; set; }
        public Nullable<int> idAccount { get; set; }
        public Nullable<int> idOrder { get; set; }
        public Nullable<int> Category_Status { get; set; }
        public Nullable<bool> confirmShip { get; set; }
        public Nullable<int> idCustomer { get; set; }
        public Nullable<bool> hideShip { get; set; }
    
        public virtual Category_Status Category_Status1 { get; set; }
        public virtual Login Login { get; set; }
        public virtual Order Order { get; set; }
    }
}
