//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comment_Product = new HashSet<Comment_Product>();
            this.listOrders = new HashSet<listOrder>();
            this.listSells = new HashSet<listSell>();
        }
    
        public int idProduct { get; set; }
        public string nameProduct { get; set; }
        public decimal priceProduct { get; set; }
        public int amountProduct { get; set; }
        public string descriptionProduct { get; set; }
        public System.DateTime datePost { get; set; }
        public int idCategory_Product { get; set; }
        public int idAccount { get; set; }
        public bool hideProduct { get; set; }
        public string imageProduct_1 { get; set; }
        public string imageProduct_2 { get; set; }
        public string imageProduct_3 { get; set; }
        public string imageProduct_4 { get; set; }
        public string Alias { get; set; }
        public Nullable<bool> confirmProduct { get; set; }
    
        public virtual Category_Product Category_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment_Product> Comment_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listOrder> listOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<listSell> listSells { get; set; }
        public virtual Login Login { get; set; }
    }
}
